### ISSUE TITLE
Autowire issue

### ISSUE THREAD

**Issue by jessequinn** [joeymasip/symfony4-api-jwt#1]
Hi Great work,

Just once thing, I get the following error with /api/user/{id}

`Cannot autowire argument $user of \"App\\Controller\\Api\\ApiUserController::detail()\": it references class \"App\\Entity\\User\" but no such service exists.`

Any idea why?

**Comment by jessequinn** [comment]
So from what i understand autowiring entities like the user is not good practice, since there may be no currently logged in user or no user at all.

maybe the following is a better approach to the user/id endpoint:

```php
<?php

namespace App\Controller\Api;

use App\Entity\User;
use JMS\Serializer\SerializerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * @Route("/user")
 */
class ApiUserController extends AbstractController
{
    private $serializer;

    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    /**
     * @Route("/{id}", name="api_user_detail", methods={"GET"})
     * @param TokenStorageInterface $token
     * @return Response
     */
    public function detail(TokenStorageInterface $token)
    {
        $user = $token->getToken() ? $token->getToken()->getUser() : null;

        if($user):
            return new Response($this->serialize($user), 200);
        else:
            return new JsonResponse([
                "code" => 401,
                "status" => "error",
                "message" => "User does not exist or you do not have access to this users information."
            ], 401);
        endif;
    }

    /**
     * Serializer (JMSSerializerBundle).
     *
     * @param User $user
     * @return mixed
     */
    protected function serialize(User $user)
    {
        return $this->serializer->serialize($user, 'json');
    }
}
```

**Comment by joeymasip** [comment]
> Hi Great work,
> 
> Just once thing, I get the following error with /api/user/{id}
> 
> `Cannot autowire argument $user of \"App\\Controller\\Api\\ApiUserController::detail()\": it references class \"App\\Entity\\User\" but no such service exists.`
> 
> Any idea why?

It seems that your entities are not being autowired as services.

Check your services.yaml, should have this code

```
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

Now, this projects is just a quick example on how to create a quick API. However, I do not recommend using autowiring at all (too much magic imo), so I would remove it completely in a real project.




> So from what i understand autowiring entities like the user is not good practice, since there may be no currently logged in user or no user at all.
> 
> maybe the following is a better approach to the user/id endpoint:
> 
> ```
> <?php
> 
> namespace App\Controller\Api;
> 
> use App\Entity\User;
> use JMS\Serializer\SerializerInterface;
> use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
> use Symfony\Component\HttpFoundation\JsonResponse;
> use Symfony\Component\HttpFoundation\Response;
> use Symfony\Component\Routing\Annotation\Route;
> use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
> 
> /**
>  * @Route("/user")
>  */
> class ApiUserController extends AbstractController
> {
>     private $serializer;
> 
>     public function __construct(SerializerInterface $serializer)
>     {
>         $this->serializer = $serializer;
>     }
> 
>     /**
>      * @Route("/{id}", name="api_user_detail", methods={"GET"})
>      * @param TokenStorageInterface $token
>      * @return Response
>      */
>     public function detail(TokenStorageInterface $token)
>     {
>         $user = $token->getToken() ? $token->getToken()->getUser() : null;
> 
>         if($user):
>             return new Response($this->serialize($user), 200);
>         else:
>             return new JsonResponse([
>                 "code" => 401,
>                 "status" => "error",
>                 "message" => "User does not exist or you do not have access to this users information."
>             ], 401);
>         endif;
>     }
> 
>     /**
>      * Serializer (JMSSerializerBundle).
>      *
>      * @param User $user
>      * @return mixed
>      */
>     protected function serialize(User $user)
>     {
>         return $this->serializer->serialize($user, 'json');
>     }
> }
> ```

The ApiUserController I created was meant to get any user providing an id. 

Your detail action just returns the same user, as long as it's logged in. Different logic.
